In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

#### Write a Python Script that captures images from your webcam video stream
#### Extracts all Faces from the image frame (using haarcascades)
#### Stores the Face information into numpy arrays

    1. Read and show video stream, capture images
    2. Detect Faces and show bounding box (haarcascade)
    3. Flatten the largest face image(gray scale) and save in a numpy array
    4. Repeat the above for multiple people to generate training data

# Integration of Web Cam

In [2]:
cam = cv2.VideoCapture(0)
# 0 means web cam number, 0 for defualt

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_alt.xml')

In [3]:
skip = 0
face_data = []
dataset_path = './data/'
offset = 10

file_name = input("Enter the name of the person : ")

Enter the name of the person : mummy


In [4]:
frame = [] # to store frame at a time

while True:
    ret, frame = cam.read()
    '''returns a boolean and frame, 
                                ret has that boolean that 
                                if frame is captured successfully'''
    if ret == False:
        continue
        
    #openCV read as BGR not RGB
    gray_frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY) 
    # return x, y, weigth, heigth
    faces = face_cascade.detectMultiScale(gray_frame) 
    
    #pick largest face (Sorted according to area)
    faces = sorted(faces, key = lambda f:f[2]*f[3])
    
    for face in faces[-1:]:
        # [-1:] See at last
        x , y , w ,h = face
        print(face)
        # draw rectangle around each face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,255,255),2)
        
        #Extract required part (Get just the face and remove every thing else)
        face_section = frame[y-offset:y+h+offset, x-offset:x+h+offset]
        face_section = cv2.resize(face_section,(100,100))
        
        if skip%5 == 0:
            face_data.append(face_section)
            print(len(face_data))
        cv2.imshow("Frame",frame)
        cv2.imshow("Face Section",face_section)
    
    skip += 1
    
    if (cv2.waitKey(1) & 0xFF) == ord('q') or len(face_data) == 25:
        cam.release()
        cv2.destroyAllWindows()
        break

[ 49 276  51  51]
1
[293 117 192 192]
[299 123 207 207]
[303 167 193 193]
[301 179 187 187]
[288 192 195 195]
[290 203 186 186]
2
[279 188 200 200]
[282 190 185 185]
[277 188 189 189]
[271 189 196 196]
[272 190 196 196]
3
[265 194 189 189]
[258 191 193 193]
[257 189 181 181]
[253 185 186 186]
[253 179 183 183]
4
[250 172 193 193]
[251 168 192 192]
[257 168 192 192]
[260 169 195 195]
[268 170 202 202]
5
[272 173 203 203]
[282 180 196 196]
[284 173 198 198]
[289 167 192 192]
[292 170 187 187]
6
[281 162 182 182]
[247 152 179 179]
[227 151 173 173]
[192 144 184 184]
[174 133 201 201]
7
[182 141 214 214]
[204 143 200 200]
[231 147 197 197]
[244 152 190 190]
[257 158 195 195]
8
[256 173 197 197]
[244 174 197 197]
[220 162 189 189]
[197 162 185 185]
[195 162 188 188]
9
[217 151 197 197]
[263 152 191 191]
[260 138 179 179]
[255 140 174 174]
[243 129 176 176]
10
[225 115 192 192]
[275 137 207 207]
[353 156 194 194]
[438 166 184 184]
[481 178 157 157]
11
[452 188 171 171]
[392 175 174 174]
[304

In [5]:
# Convert our face list array into a numpy array
face_data = np.asarray(face_data)
face_data = face_data.reshape((face_data.shape[0],-1))
print(face_data.shape)

# Save this data into file system
np.save(dataset_path+file_name+'.npy',face_data)
print("Data Successfully save at "+dataset_path+file_name+'.npy')

cam.release()
cv2.destroyAllWindows()

(25, 30000)
Data Successfully save at ./data/mummy.npy


### a[-1:] ??? working

In [6]:
a = [[1,2,3,4],[5,6,7,8,9]]

In [7]:
a[-1:]

[[5, 6, 7, 8, 9]]

In [8]:
a[-1]

[5, 6, 7, 8, 9]

In [10]:
cam.release()